changesetBaseRefs:
  - latest
  - origin/latest

enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard

nmHoistingLimits: workspaces

nmSelfReferences: false

nodeLinker: node-modules

npmPublishAccess: public

preferAggregateCacheInfo: true

yarnPath: .yarn/releases/yarn-4.0.0-rc.21.git.20220926.hash-8ff27df.cjs
